// Automatically generated by MockGen. DO NOT EDIT!
// Source: fromflags.go

package client

import (
	gomock "github.com/golang/mock/gomock"
	stats "github.com/turbinelabs/api/service/stats"
	executor "github.com/turbinelabs/nonstdlib/executor"
	log "log"
)

// Mock of FromFlags interface
type MockFromFlags struct {
	ctrl     *gomock.Controller
	recorder *_MockFromFlagsRecorder
}

// Recorder for MockFromFlags (not exported)
type _MockFromFlagsRecorder struct {
	mock *MockFromFlags
}

func NewMockFromFlags(ctrl *gomock.Controller) *MockFromFlags {
	mock := &MockFromFlags{ctrl: ctrl}
	mock.recorder = &_MockFromFlagsRecorder{mock}
	return mock
}

func (_m *MockFromFlags) EXPECT() *_MockFromFlagsRecorder {
	return _m.recorder
}

func (_m *MockFromFlags) Validate() error {
	ret := _m.ctrl.Call(_m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) Validate() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate")
}

func (_m *MockFromFlags) Make(_param0 executor.Executor, _param1 *log.Logger) (stats.StatsService, error) {
	ret := _m.ctrl.Call(_m, "Make", _param0, _param1)
	ret0, _ := ret[0].(stats.StatsService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockFromFlagsRecorder) Make(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Make", arg0, arg1)
}

func (_m *MockFromFlags) APIKey() string {
	ret := _m.ctrl.Call(_m, "APIKey")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockFromFlagsRecorder) APIKey() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "APIKey")
}
