// Automatically generated by MockGen. DO NOT EDIT!
// Source: client.go

package client

import (
	gomock "github.com/golang/mock/gomock"
	stats "github.com/turbinelabs/api/service/stats"
	executor "github.com/turbinelabs/nonstdlib/executor"
)

// Mock of internalStatsClient interface
type MockinternalStatsClient struct {
	ctrl     *gomock.Controller
	recorder *_MockinternalStatsClientRecorder
}

// Recorder for MockinternalStatsClient (not exported)
type _MockinternalStatsClientRecorder struct {
	mock *MockinternalStatsClient
}

func NewMockinternalStatsClient(ctrl *gomock.Controller) *MockinternalStatsClient {
	mock := &MockinternalStatsClient{ctrl: ctrl}
	mock.recorder = &_MockinternalStatsClientRecorder{mock}
	return mock
}

func (_m *MockinternalStatsClient) EXPECT() *_MockinternalStatsClientRecorder {
	return _m.recorder
}

func (_m *MockinternalStatsClient) IssueRequest(_param0 *stats.Payload, _param1 executor.CallbackFunc) error {
	ret := _m.ctrl.Call(_m, "IssueRequest", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockinternalStatsClientRecorder) IssueRequest(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IssueRequest", arg0, arg1)
}
