// Automatically generated by MockGen. DO NOT EDIT!
// Source: client.go

package client

import (
	gomock "github.com/golang/mock/gomock"
	stats "github.com/turbinelabs/stats"
)

// Mock of Stats interface
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *_MockStatsRecorder
}

// Recorder for MockStats (not exported)
type _MockStatsRecorder struct {
	mock *MockStats
}

func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &_MockStatsRecorder{mock}
	return mock
}

func (_m *MockStats) EXPECT() *_MockStatsRecorder {
	return _m.recorder
}

func (_m *MockStats) Forward(_param0 stats.StatsPayload) (stats.Result, error) {
	ret := _m.ctrl.Call(_m, "Forward", _param0)
	ret0, _ := ret[0].(stats.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStatsRecorder) Forward(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Forward", arg0)
}
