// Code generated by MockGen. DO NOT EDIT.
// Source: latching_sender.go

package stats

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// mockLatchableSender is a mock of latchableSender interface
type mockLatchableSender struct {
	ctrl     *gomock.Controller
	recorder *mockLatchableSenderMockRecorder
}

// mockLatchableSenderMockRecorder is the mock recorder for mockLatchableSender
type mockLatchableSenderMockRecorder struct {
	mock *mockLatchableSender
}

// newMockLatchableSender creates a new mock instance
func newMockLatchableSender(ctrl *gomock.Controller) *mockLatchableSender {
	mock := &mockLatchableSender{ctrl: ctrl}
	mock.recorder = &mockLatchableSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *mockLatchableSender) EXPECT() *mockLatchableSenderMockRecorder {
	return m.recorder
}

// Gauge mocks base method
func (m *mockLatchableSender) Gauge(stat string, value float64, tags ...string) {
	varargs := []interface{}{stat, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Gauge", varargs...)
}

// Gauge indicates an expected call of Gauge
func (mr *mockLatchableSenderMockRecorder) Gauge(stat, value interface{}, tags ...interface{}) *gomock.Call {
	varargs := append([]interface{}{stat, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*mockLatchableSender)(nil).Gauge), varargs...)
}

// Count mocks base method
func (m *mockLatchableSender) Count(stat string, count float64, tags ...string) {
	varargs := []interface{}{stat, count}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Count", varargs...)
}

// Count indicates an expected call of Count
func (mr *mockLatchableSenderMockRecorder) Count(stat, count interface{}, tags ...interface{}) *gomock.Call {
	varargs := append([]interface{}{stat, count}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*mockLatchableSender)(nil).Count), varargs...)
}

// Histogram mocks base method
func (m *mockLatchableSender) Histogram(stat string, value float64, tags ...string) {
	varargs := []interface{}{stat, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Histogram", varargs...)
}

// Histogram indicates an expected call of Histogram
func (mr *mockLatchableSenderMockRecorder) Histogram(stat, value interface{}, tags ...interface{}) *gomock.Call {
	varargs := append([]interface{}{stat, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Histogram", reflect.TypeOf((*mockLatchableSender)(nil).Histogram), varargs...)
}

// Timing mocks base method
func (m *mockLatchableSender) Timing(stat string, value time.Duration, tags ...string) {
	varargs := []interface{}{stat, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Timing", varargs...)
}

// Timing indicates an expected call of Timing
func (mr *mockLatchableSenderMockRecorder) Timing(stat, value interface{}, tags ...interface{}) *gomock.Call {
	varargs := append([]interface{}{stat, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timing", reflect.TypeOf((*mockLatchableSender)(nil).Timing), varargs...)
}

// LatchedHistogram mocks base method
func (m *mockLatchableSender) LatchedHistogram(arg0 string, arg1 LatchedHistogram, arg2 ...string) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LatchedHistogram", varargs...)
}

// LatchedHistogram indicates an expected call of LatchedHistogram
func (mr *mockLatchableSenderMockRecorder) LatchedHistogram(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatchedHistogram", reflect.TypeOf((*mockLatchableSender)(nil).LatchedHistogram), varargs...)
}
