// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/falun/genny

package requestcontext

import (
	"net/http"

	"github.com/turbinelabs/server/handler/requestcontext"
)

type RequestContext struct {
	requestcontext.RequestContext
}

func New(req *http.Request) RequestContext {
	return RequestContext{requestcontext.New(req)}
}

func NewWithFunctions(
	req *http.Request,
	setfn requestcontext.SetFn,
	getfn requestcontext.GetFn,
	delfn requestcontext.DeleteFn,
) RequestContext {
	return RequestContext{
		requestcontext.NewWithFunctions(req, setfn, getfn, delfn),
	}
}
