// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/falun/genny

package requestcontext

import (
	"net/http"
	"testing"

	"github.com/turbinelabs/api"
	"github.com/turbinelabs/test/assert"
)

func TestSetOrgKey(t *testing.T) {
	req := &http.Request{}
	c, st, gt, dt := mkCtx(req)

	v := TmplOrgKeyValue
	c.SetOrgKey(v)

	assert.Equal(t, st.calledCount, 1)
	assert.Equal(t, dt.calledCount, 0)
	assert.Equal(t, gt.calledCount, 0)
	assert.Equal(t, st.calledOnReq, req)
	assert.DeepEqual(t, st.calledFor, OrgKey)
	assert.DeepEqual(t, st.calledWith, v)
}

func TestGetOrgKeyOk(t *testing.T) {
	req := &http.Request{}
	c, st, gt, dt := mkCtx(req)
	v := TmplOrgKeyValue

	gt.returnValue = v
	gt.returnBool = true

	gotv, gotb := c.GetOrgKey()

	assert.Equal(t, st.calledCount, 0)
	assert.Equal(t, gt.calledCount, 1)
	assert.Equal(t, dt.calledCount, 0)
	assert.Equal(t, gt.calledOnReq, req)
	assert.DeepEqual(t, gt.calledFor, OrgKey)
	assert.DeepEqual(t, gotv, v)
	assert.Equal(t, gotb, true)
}

func TestGetOrgKeyNotOk(t *testing.T) {
	req := &http.Request{}
	c, st, gt, dt := mkCtx(req)
	v := TmplOrgKeyValue

	gt.returnValue = v
	gt.returnBool = false

	gotv, gotb := c.GetOrgKey()
	var wantv api.OrgKey

	assert.Equal(t, st.calledCount, 0)
	assert.Equal(t, gt.calledCount, 1)
	assert.Equal(t, dt.calledCount, 0)
	assert.Equal(t, gt.calledOnReq, req)
	assert.DeepEqual(t, gt.calledFor, OrgKey)
	assert.DeepEqual(t, gotv, wantv)
	assert.Equal(t, gotb, false)
}

func TestUnsetOrgKey(t *testing.T) {
	req := &http.Request{}
	c, st, gt, dt := mkCtx(req)

	c.UnsetOrgKey()

	assert.Equal(t, st.calledCount, 0)
	assert.Equal(t, gt.calledCount, 0)
	assert.Equal(t, dt.calledCount, 1)
	assert.Equal(t, dt.calledOnReq, req)
	assert.DeepEqual(t, dt.calledFor, OrgKey)
}
