// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/falun/genny

package requestcontext

import "github.com/turbinelabs/api"

func (rc RequestContext) SetOrgKey(v api.OrgKey) {
	rc.Set(OrgKey, v)
}

var zeroValOrgKey api.OrgKey

func (rc RequestContext) GetOrgKey() (api.OrgKey, bool) {
	keyRaw, ok := rc.Get(OrgKey)
	if !ok {
		return zeroValOrgKey, false
	}

	cast, castOk := keyRaw.(api.OrgKey)
	if !castOk {
		return zeroValOrgKey, false
	}

	return cast, true
}

func (rc RequestContext) UnsetOrgKey() {
	rc.Delete(OrgKey)
}
